# syntax=docker/dockerfile:1

FROM python:3.10-slim-bullseye 

LABEL maintainer="Kevin Flynn <Creator4983@encom.com>"  

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /workspace
ENV MY_DIR /workspace
COPY . ${MY_DIR}

# apt-cache policy apt-utils | grep Candidate
RUN apt-get update \
    && apt-get --no-install-recommends -y install apt-utils=2.2.4 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

